DROP TABLE IF EXISTS CONFIGURATION;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS CLAIM;
DROP TABLE IF EXISTS CLAIMANT;
DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS BOUNDARY;

CREATE TABLE CONFIGURATION
(NAME VARCHAR(255) PRIMARY KEY,
VALUE VARCHAR(255));

CREATE TABLE CLAIMANT
(CLAIMANT_ID VARCHAR(255) PRIMARY KEY,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
EMAIL_ADDRESS VARCHAR(63),
POSTAL_ADDRESS VARCHAR(255),
MOBILE_PHONE_NUMBER VARCHAR(255));

CREATE TABLE BOUNDARY
(BOUNDARY_ID VARCHAR(255), 
BOUNDARY_PT_LAT DECIMAL(15,10), 
BOUNDARY_PT_LON DECIMAL(15,10), 
BOUNDARY_PT_SEQUENCE VARCHAR(255),
PRIMARY KEY (BOUNDARY_ID, BOUNDARY_PT_SEQUENCE));

CREATE TABLE LOCATION
(LOCATION_ID VARCHAR(255) PRIMARY KEY, 
LOCATION_LAT DECIMAL(15,10), 
LOCATION_LON DECIMAL(15,10));

CREATE TABLE CLAIM
(CLAIM_ID VARCHAR(255) PRIMARY KEY, 
CLAIMANT_ID VARCHAR(255), 
BOUNDARY_ID VARCHAR(255),
FOREIGN KEY (BOUNDARY_ID)
REFERENCES BOUNDARY(BOUNDARY_ID),
FOREIGN KEY (CLAIMANT_ID)
REFERENCES CLAIMANT(CLAIMANT_ID));

CREATE TABLE DOCUMENT
(DOCUMENT_ID VARCHAR(255) PRIMARY KEY, 
CLAIM_ID VARCHAR(255), 
MD5SUM VARCHAR(255), 
PATH VARCHAR(255),
FOREIGN KEY (CLAIM_ID)
REFERENCES CLAIM(CLAIM_ID));