DROP TABLE IF EXISTS CONFIGURATION;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS CLAIM;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS BOUNDARY;

CREATE TABLE CONFIGURATION
(NAME VARCHAR(255) PRIMARY KEY,
VALUE VARCHAR(255));

CREATE TABLE PERSON
(PERSON_ID VARCHAR(255) PRIMARY KEY,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
DATE_OF_BIRTH DATE,
PLACE_OF_BIRTH VARCHAR(255),
EMAIL_ADDRESS VARCHAR(63),
POSTAL_ADDRESS VARCHAR(255),
MOBILE_PHONE_NUMBER VARCHAR(255),
CONTACT_PHONE_NUMBER VARCHAR(255));

CREATE TABLE BOUNDARY
(BOUNDARY_ID VARCHAR(255), 
SEQUENCE_NUMBER INT,
GPS_LAT DECIMAL(15,10), 
GPS_LON DECIMAL(15,10), 
MAP_LAT DECIMAL(15,10), 
MAP_LON DECIMAL(15,10), 
PRIMARY KEY (BOUNDARY_ID, SEQUENCE_NUMBER));

CREATE TABLE LOCATION
(LOCATION_ID VARCHAR(255) PRIMARY KEY, 
LOCATION_LAT DECIMAL(15,10), 
LOCATION_LON DECIMAL(15,10));

CREATE TABLE CLAIM
(CLAIM_ID VARCHAR(255) PRIMARY KEY, 
DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
PERSON_ID VARCHAR(255), 
BOUNDARY_ID VARCHAR(255),
CHALLENGED_CLAIM_ID VARCHAR(255),
FOREIGN KEY (CHALLENGED_CLAIM_ID)
REFERENCES CLAIM(CLAIM_ID),
FOREIGN KEY (BOUNDARY_ID)
REFERENCES BOUNDARY(BOUNDARY_ID),
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON(PERSON_ID));

CREATE INDEX CHALLENGE_IDX ON CLAIM(CHALLENGED_CLAIM_ID);

CREATE TABLE DOCUMENT
(DOCUMENT_ID VARCHAR(255) PRIMARY KEY, 
CLAIM_ID VARCHAR(255), 
FILE_NAME VARCHAR(255), 
MD5SUM VARCHAR(255), 
PATH VARCHAR(255),
FOREIGN KEY (CLAIM_ID)
REFERENCES CLAIM(CLAIM_ID));
