CREATE TABLE LANGUAGE
(ID INT auto_increment PRIMARY KEY,
 CODE VARCHAR(255) NOT NULL,
 DISPLAY_VALUE VARCHAR(255) NOT NULL,
 ACTIVE BOOLEAN NOT NULL,
 ITEM_ORDER INT NOT NULL);
 
CREATE UNIQUE INDEX LANGUAGE_IDX ON LANGUAGE(CODE);


UPDATE CONFIGURATION SET VALUE='1.1.0' WHERE NAME='DBVERSION' AND VALUE='1.0.0';