MERGE INTO CONFIGURATION(CONFIGURATION_ID, NAME, VALUE) KEY (CONFIGURATION_ID) SELECT '2', 'PROTOVERSION', '1.0' FROM DUAL;

UPDATE CONFIGURATION SET VALUE='1.3.0' WHERE NAME='DBVERSION' AND VALUE='1.2.0';