CREATE TABLE LANGUAGE
(ID INT auto_increment PRIMARY KEY,
CODE VARCHAR(255) NOT NULL,
DISPLAY_VALUE VARCHAR(255) NOT NULL,
ACTIVE BOOLEAN NOT NULL,
IS_DEFAULT BOOLEAN NOT NULL,
LTR BOOLEAN NOT NULL,
ITEM_ORDER INT NOT NULL);

CREATE UNIQUE INDEX LANGUAGE_IDX ON LANGUAGE(CODE);
CREATE INDEX DEFAULT_LANGUAGE_IDX ON LANGUAGE(IS_DEFAULT);


UPDATE CONFIGURATION SET VALUE='1.1.0' WHERE NAME='DBVERSION' AND VALUE='1.0.0';